### ISSUE TITLE
Unify the behavior of POST method to follow Requests library's POST method - add data as an argument

### ISSUE THREAD

**Issue by Namupala** [dlt-hub/dlt#2289]
### Feature description

From the [dlt docs](https://dlthub.com/docs/general-usage/http/rest-client#restclientget-and-restclientpost-methods)

> These methods work similarly to the [get()](https://docs.python-requests.org/en/latest/api/#requests.get) and [post()](https://docs.python-requests.org/en/latest/api/#requests.post) functions from the Requests library.

However, to my knowledge passing in data as an argument is currently not possible. Therefore sending not-form-encoded data in the body of Request is not possible.

When trying to fetch data from an API that expects json payload to be of type string (not form-encoded) the following approach fails. 

```
import json

PAYLOAD = json.dumps(
	{
		"SearchKeys": {
			"CriteriaKey": "SearchCriteria:-998670234;;Filters:371857150;Sort:-1587235143",
			"ScratchpadKey": "a7f9b70c-e563-4ab3-b9ce-22f61e45236d"
		},
		"Criteria": {
			"ClassName": "resource_name",
			"IncludeWorkflow": False
		},
		"Filtering": {
			"Items": []
		},
		"Paging": {
			"Page": 1,
			"PageSize": 4
		},
		"Sorting": {
			"Items": [
				{
					"PropertyName": "description",
					"Direction": 1
				}
			]
		}
	}
)

source_config: RESTAPIConfig = {
"client": {
	"base_url": base_url,
	"auth": auth
},

"resources": 
	[
		{
			"name": "rest_list_all_posts",
			"table_name": "test_table",
			"endpoint": {
				"data_selector": "$", # Get the full response
				"path": "/search/",
				"paginator": page_paginator,
				"method": "POST",
				"json": PAYLOAD,
				
			},
		},
	]
}
```
Error trace:
```
For Endpoint: In path ./resources[0]/endpoint: field 'json' with value {"SearchKeys": {"CriteriaKey": "SearchCriteria:-998670234;;Filters:371857150;Sort:-1587235143", "ScratchpadKey": "a7f9b70c-e563-4ab3-b9ce-22f61e45236d"}, "Criteria": {"ClassName": "resource_name", "IncludeWorkflow": false}, "Filtering": {"Items": []}, "Paging": {"Page": 1, "PageSize": 4}, "Sorting": {"Items": [{"PropertyName": "description", "Direction": 1}]}} has invalid type 'str' while 'dict' is expected
```

### Are you a dlt user?

Yes, I'm already a dlt user.

### Use case

From [requests docs](https://requests.readthedocs.io/en/latest/user/quickstart/#more-complicated-post-requests)

> There are times that you may want to send data that is not form-encoded. If you pass in a string instead of a dict, that data will be posted directly. 

> For example, the GitHub API v3 accepts JSON-Encoded POST/PATCH data:
```
import json

url = 'https://api.github.com/some/endpoint'
payload = {'some': 'data'}

r = requests.post(url, data=json.dumps(payload))
```

Implementing this would enhance the ability to fetch data from different kinds of APIs

### Proposed solution
Unify the behavior of POST method to follow the requests library POST method by adding data as an argument. Alternatively allow json payload to be of type string (not form-encoded) using json.dumps() in endpoint configuration.

**Comment by burnash** [comment]
Hi @Namupala, sorry for the late response. In your example, why are you serializing the dict (`PAYLOAD`) with `json.dumps` and not just passing the `PAYLOAD` directly to `json` in the config?

**Comment by Namupala** [comment]
Hi, @burnash

the API, from which I tried to retrieve data, required the data to be posted in a **not form-encoded format.** 
>There are times that you may want to send data that is not form-encoded. If you pass in a string instead of a dict, that data will be posted directly.

To my understanding `RESTAPIConfig` endpoint configuration currently doesn't support `data` parameter in a similar fashion as `Request` does (see the example above). 

> The fields in the endpoint configuration are:

```
path: The path to the API endpoint. By default this path is appended to the given base_url. If this is a fully qualified URL starting with http: or https: it will be used as-is and base_url will be ignored.
method: The HTTP method to be used. The default is GET.
params: Query parameters to be sent with each request. For example, sort to order the results or since to specify [incremental loading](https://dlthub.com/docs/dlt-ecosystem/verified-sources/rest_api/basic#incremental-loading). This is also may be used to define [resource relationships](https://dlthub.com/docs/dlt-ecosystem/verified-sources/rest_api/basic#define-resource-relationships).
json: The JSON payload to be sent with the request (for POST and PUT requests).
paginator: Pagination configuration for the endpoint. See the [pagination](https://dlthub.com/docs/dlt-ecosystem/verified-sources/rest_api/basic#pagination) section for more details.
data_selector: A JSONPath to select the data from the response. See the [data selection](https://dlthub.com/docs/dlt-ecosystem/verified-sources/rest_api/basic#data-selection) section for more details.
response_actions: A list of actions that define how to process the response data. See the [response actions](https://dlthub.com/docs/dlt-ecosystem/verified-sources/rest_api/advanced#response-actions) section for more details.
incremental: Configuration for [incremental loading](https://dlthub.com/docs/dlt-ecosystem/verified-sources/rest_api/basic#incremental-loading).
```
Posting the data as a dict using `json` resulted in an error in my case.

Implementing similar behaviour of Request's data functionality would be awesome.

**Comment by burnash** [comment]
Thank you for elaborating, @Namupala. 

As far as I know, when you use `json` parameter in Requests, the data is not form-urlencoded, but rather [serialized and sent in the request body with `content_type = "application/json"`](https://github.com/psf/requests/blob/90fee0876aea97c639b3bf698d83a12876d2f160/src/requests/models.py#L504-L515). That's the reason I was wondering about why you're passing a string to `json` in the config.

> To my understanding RESTAPIConfig endpoint configuration currently doesn't support data parameter in a similar fashion as Request does (see the example above).

This is true. `data` is not yet supported. So far we haven't come across a use case for this. Would you be interested in contributing a PR for this?

If the API you're working with doesn't let you use `application/json` content type, you may want to try setting a different `Content-Type` via custom headers at the endpoint level in the config. It's not yet documented properly, here's a PR with missing docs #2747 

Please let me know if this helps.

**Comment by wischmcj** [comment]
@burnash I might have a use case for you, and I also implemented this locally so I'd be happy to contribute to a pr if @Namupala is not interested. Let me know what you think!

**Use Case:**
Using the dlt REST source to pull data from a SOAP endpoint. You can use the requests library for this, and the only thing that you have to change is to:
1. pass the xml for the api in the data field. 
2. update the encoding header

**Current Workaround:**
I ended up using a paginator for this, which you can find the code for [here](https://gist.github.com/wischmcj/76ee3fc2e93fefee6a863fc911d8ffbb). This works fine, but it seems a bit hacky to me, and I would love to be able to either:

1. pass the correctly formatted response through the config via a 'data' field
2. Pass a custom SOAP API Client (also shown in the code above) to handle the logic

FWIW, allowing custom clients _seems_ pretty easy to implement, so I'd be happy to take a crack at that as well, if yall are interested.

**Comment by burnash** [comment]
Hey @wischmcj, thanks for the details and especially for the code snippet. This is really interesting, as we occasionally have users asking about extracting data from SOAP.

Could you share what advantages you see in using dlt's `rest_api`, compared to using [Zeep](https://docs.python-zeep.org/en/master/) and wrapping the response in a dlt resource?

**Comment by henry-yu-gce** [comment]
Wanted to add that we also have a use case where we have an API that only accepts form-encoded data in the body (the `data` parameter) or else the API won't return anything. 

In our case, this code snippet passes

``` python
CLIENT_ID = "OurUsername"
CLIENT_SECRET = "OUR-PASSWORD"
auth_url = "https://<example_website.com>/oauth/connect/token"

params = {
    "client_id" : CLIENT_ID,
    "client_secret": CLIENT_SECRET,
     "grant_type" : "client_credentials"
}

r = requests.post(
    auth_url,
    data=params, 
)
print(r.status_code)
> 200 

```

While this fails (we only changed the `data` parameter into `json`. Even if we add in the `header` to specify form encoded, it still fails (with or without the header) 
``` python
CLIENT_ID = "OurUsername"
CLIENT_SECRET = "OUR-PASSWORD"
auth_url = "https://<example_website.com>/oauth/connect/token"
headers = {
    "Content-Type": "application/x-www-form-urlencoded"
}
params = {
    "client_id" : CLIENT_ID,
    "client_secret": CLIENT_SECRET,
     "grant_type" : "client_credentials"
}

r = requests.post(
    auth_url,
    json=params, 
    headers=headers
)
print(r.status_code)
> 400
```

This example is the simplest from that REST API provider and gets a Bearer token. However, all other REST API endpoints from that providers follow the same structure and expects `x-www-form-urlencoded` request body payload.

**Comment by burnash** [comment]
Thanks for the input @henry-yu-gce, we'll add support for `data` param very soon.
